// Generated by CoffeeScript 1.6.3
(function() {
  var FlickrImageFinder, Navigation, app, consolidate, express, geohashFromRequest, handleGeohash, handleImages, handleNav, imageFinder, logfmt, maxCrawlDepth, navigation, port, _,
    _this = this;

  express = require("express");

  logfmt = require("logfmt");

  _ = require("underscore")._;

  app = express();

  app.use(logfmt.requestLogger());

  app.all('*', function(req, resp, next) {
    resp.header("Access-Control-Allow-Origin", "*");
    resp.header("Access-Control-Allow-Headers", "X-Requested-With");
    return next();
  });

  consolidate = require('consolidate');

  app.engine('html', consolidate.mustache);

  app.set('view engine', 'html');

  app.set('views', __dirname + '/views');

  app.use(express["static"](__dirname + '/client'));

  app.get('/about', function(req, resp) {
    return resp.render("about", {
      thisPackage: require("./package.json")
    });
  });

  maxCrawlDepth = 4;

  app.get('/:geohash/crawl', function(req, resp) {
    var geohash, hashesBelow;
    geohash = req.params.geohash;
    hashesBelow = geohash.length <= maxCrawlDepth ? navigation.hashesBelow(geohash) : [];
    return resp.render("crawl", {
      thisPackage: require("./package.json"),
      hashesBelow: hashesBelow
    });
  });

  app.get('/crawl', function(req, resp) {
    return resp.render("crawl", {
      thisPackage: require("./package.json"),
      hashesBelow: navigation.hashesBelow("")
    });
  });

  geohashFromRequest = function(req) {
    if (req.params.geohash != null) {
      return req.params.geohash;
    } else {
      return "";
    }
  };

  Navigation = require("./server/Navigation");

  navigation = new Navigation();

  handleNav = function(req, resp) {
    var geohash,
      _this = this;
    geohash = geohashFromRequest(req);
    return navigation.navigateFrom(geohash, function(result) {
      console.dir(result);
      return resp.send({
        'geohash': geohash,
        'navigation': result
      });
    });
  };

  app.get('/navigation', handleNav);

  app.get('/:geohash/navigation', handleNav);

  FlickrImageFinder = require("./server/FlickrImageFinder");

  imageFinder = new FlickrImageFinder(process.env['FLICKR_API_KEY'], "s");

  handleImages = function(req, resp) {
    var geohash, related,
      _this = this;
    geohash = geohashFromRequest(req);
    related = _.map(navigation.hashesBelow(geohash), function(below) {
      return {
        name: below,
        href: "/" + below + "/images"
      };
    });
    return imageFinder.findImages(geohash, function(result) {
      var secondsExpiry;
      console.dir(result);
      secondsExpiry = 24 * 60 * 60;
      resp.setHeader("Cache-Control", "public, max-age=" + secondsExpiry);
      resp.setHeader("Expires", new Date(Date.now() + (secondsExpiry * 1000)).toUTCString());
      return resp.send({
        'geohash': geohash,
        'related': related,
        'images': result
      });
    }, function() {
      console.log("Error");
      return resp.sendStatus(404);
    });
  };

  app.get('/images', handleImages);

  app.get('/:geohash/images', handleImages);

  handleGeohash = function(req, resp) {
    return resp.render("geohash", {
      thisPackage: require("./package.json")
    });
  };

  app.get('/:geohash', handleGeohash);

  app.get('/', handleGeohash);

  port = process.env.PORT || 9000;

  console.log("Attempting to listen on %s ...", port);

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);

/*
//@ sourceMappingURL=web.map
*/
