// Generated by CoffeeScript 1.6.3
(function() {
  var Application,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Application = (function() {
    function Application(location) {
      this.location = location;
      this.run = __bind(this.run, this);
      console.log("Loaded");
      console.log("using:");
      console.dir(this.location);
      this.model = {
        images: ko.observableArray([])
      };
    }

    Application.prototype.run = function() {
      var _this = this;
      return $.getJSON(this.location, function(data, status) {
        console.dir(data);
        console.dir(status);
        if (status === "success" && (data.images != null)) {
          console.dir(data.images);
          return _this.model.images(data.images);
        } else {
          return console.log("Failed");
        }
      });
    };

    return Application;

  })();

  window.Application = Application;

}).call(this);

/*
//@ sourceMappingURL=Application.map
*/
