// Generated by CoffeeScript 1.6.3
(function() {
  var Foop;

  Foop = (function() {
    function Foop() {
      console.log("Loaded");
    }

    return Foop;

  })();

  window.Foop = Foop;

}).call(this);

/*
//@ sourceMappingURL=Foop.map
*/
