// Generated by CoffeeScript 1.6.3
(function() {
  var MapBackground,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MapBackground = (function() {
    function MapBackground(selector, navigation) {
      this.selector = selector;
      this.navigation = navigation;
      this._navigationChanged = __bind(this._navigationChanged, this);
      this.map = null;
      this.navigation.subscribe(this._navigationChanged);
    }

    MapBackground.prototype._navigationChanged = function() {
      if (this.map == null) {
        this.map = L.map(this.selector).setView([51.505, -0.09], 13);
        return L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          attribution: 'Map data © OpenStreetMap contributors',
          maxZoom: 18
        }).addTo(this.map);
      }
    };

    return MapBackground;

  })();

  window.MapBackground = MapBackground;

}).call(this);

/*
//@ sourceMappingURL=MapBackground.map
*/
