// Generated by CoffeeScript 1.6.3
(function() {
  var Navigation, geohash, util, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  geohash = require("ngeohash");

  _ = require("underscore")._;

  util = require("util");

  Navigation = (function() {
    function Navigation() {
      this._toUrl = __bind(this._toUrl, this);
      this._downFrom = __bind(this._downFrom, this);
      this.navigateFrom = __bind(this.navigateFrom, this);
    }

    Navigation.prototype.navigateFrom = function(geohash, success) {
      var nav;
      nav = {
        'descend': this._downFrom(geohash)
      };
      if (geohash.length > 1) {
        nav.ascend = this._toUrl("/%s/")(geohash.substring(0, geohash.length - 1));
      }
      return success(nav);
    };

    Navigation.prototype._downFrom = function(baseGeohash) {
      var base32, char, geohashes, rows,
        _this = this;
      base32 = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k', 'm', 'n', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
      geohashes = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = base32.length; _i < _len; _i++) {
          char = base32[_i];
          _results.push(baseGeohash + char);
        }
        return _results;
      })();
      rows = _.chain(geohashes).groupBy(function(g) {
        return geohash.decode(g).latitude;
      }).values().reverse().value();
      rows = _.map(rows, function(r) {
        return _.chain(r).sortBy(function(g) {
          return geohash.decode(g).longitude;
        }).map(_this._toUrl("/%s/")).value();
      });
      return {
        columns: rows[0].length,
        rows: rows.length,
        values: rows
      };
    };

    Navigation.prototype._toUrl = function(format) {
      var _this = this;
      return function(geohash) {
        return {
          name: geohash,
          href: util.format(format, geohash)
        };
      };
    };

    return Navigation;

  })();

  module.exports = Navigation;

}).call(this);

/*
//@ sourceMappingURL=Navigation.map
*/
